
services:
jellyfin:
image: jellyfin/jellyfin:latest
container_name: jellyfin
restart: unless-stopped
ports:
  - "8096:8096"

volumes:
  - jellyfin_config:/config
  - jellyfin_cache:/cache
  - "C:/docker_data/data:/data:ro"
jellyseerr:
image: fallenbagel/jellyseerr:latest
container_name: jellyseerr
restart: unless-stopped
ports:
  - "5055:5055"

volumes:
  - jellyseerr_config:/app/config

depends_on:
  jellyfin:
    condition: service_started
volumes:
jellyfin_config:
jellyfin_cache:
jellyseerr_config:
